default_install_hook_types:
  - pre-commit
  - commit-msg
default_stages:
  - pre-commit
  - manual

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
        files: \.(yaml|yml)$
        exclude: \.github/workflows/
      - id: end-of-file-fixer
        files: \.(py|md|yaml|yml|c|cc|cxx|cpp|h|hpp|hxx|cu|cuh)$
      - id: trailing-whitespace
        files: \.(py|md|yaml|yml|c|cc|cxx|cpp|h|hpp|hxx|cu|cuh)$
      - id: check-added-large-files
        name: Check for large files
        args: ['--maxkb=1000']
      - id: detect-private-key
        name: Detect private keys

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.17
    hooks:
      - id: ruff
        name: Run Linter Check (Ruff)
        types_or: [python, pyi, jupyter]
        args: [--fix]
      - id: ruff-format
        name: Run Formatter (Ruff)
        types_or: [python, pyi, jupyter]

  # Conventional Commits message check
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args:
          - feat
          - fix
          - docs
          - style
          - refactor
          - perf
          - test
          - build
          - ci
          - chore
          - revert
