// Graph-compiler interface for the embedded TPC activation binaries.
#include <algorithm>
#include <cstdint>
#include <cstring>
#include <initializer_list>

#include "gc_interface.h"
#include "tpc_kernel_lib_interface.h"

struct KernelBinary {
    const char* name;
    const unsigned char* data;
    std::size_t size;
    int dtype;
    bool backward;
    bool gated;
    int family;
    int kind;
    int direction;
};

// Generated by setup.py from the actual tpc-clang output, never placeholder ISA.
#include "kernel_binaries.h"
#include "normalization_glue.h"
#include "linear_glue.h"
#include "optimizer_glue.h"
#include "quantized_optimizer_glue.h"
#include "factored_stats_glue.h"
#include "embedding_glue.h"
#include "attention_glue.h"
#include "paged_cache_glue.h"
#include "conv_glue.h"
#include "topk_glue.h"
#include "moe_glue.h"
#include "moe_align_glue.h"
#include "fused_moe_glue.h"
#include "kda_glue.h"
#include "seg_la_glue.h"

extern "C" tpc_lib_api::GlueCodeReturn GetKernelGuids(
    tpc_lib_api::DeviceId device, uint32_t* count, tpc_lib_api::GuidInfo* guids
) {
    const uint32_t available = device == ARENO_TPC_DEVICE ? sizeof(binaries) / sizeof(binaries[0]) : 0;
    if (guids != nullptr) {
        for (uint32_t i = 0; i < std::min(*count, available); ++i) {
            std::strcpy(guids[i].name, binaries[i].name);
        }
    }
    *count = available;
    return tpc_lib_api::GLUE_SUCCESS;
}

static tpc_lib_api::GlueCodeReturn instantiate_activation(
    tpc_lib_api::HabanaKernelParams* params, tpc_lib_api::HabanaKernelInstantiation* instance, const KernelBinary* binary
) {
    const unsigned input_count = binary->backward ? 2 : 1;
    if (params->inputTensorNr != input_count) {
        params->inputTensorNr = input_count;
        return tpc_lib_api::GLUE_INCOMPATIBLE_INPUT_COUNT;
    }
    if (params->outputTensorNr != 1) {
        params->outputTensorNr = 1;
        return tpc_lib_api::GLUE_INCOMPATIBLE_OUTPUT_COUNT;
    }
    const auto dtype = binary->dtype == 0 ? tpc_lib_api::DATA_F32
        : binary->dtype == 1 ? tpc_lib_api::DATA_BF16 : tpc_lib_api::DATA_F16;
    bool dtype_mismatch = false;
    for (unsigned i = 0; i < input_count; ++i) {
        dtype_mismatch |= params->inputTensors[i].geometry.dataType != dtype;
        params->inputTensors[i].geometry.dataType = dtype;
    }
    dtype_mismatch |= params->outputTensors[0].geometry.dataType != dtype;
    params->outputTensors[0].geometry.dataType = dtype;
    if (dtype_mismatch) return tpc_lib_api::GLUE_INCOMPATIBLE_DATA_TYPE;

    const auto& input = params->inputTensors[0].geometry;
    auto& output = params->outputTensors[0].geometry;
    const uint64_t output_channels = binary->gated && binary->backward ? 2 : 1;
    if (output.dims != 3 || output.maxSizes[0] != input.maxSizes[0]
        || output.maxSizes[1] != output_channels || output.maxSizes[2] != input.maxSizes[2]) {
        output.dims = 3;
        output.maxSizes[0] = input.maxSizes[0];
        output.maxSizes[1] = output_channels;
        output.maxSizes[2] = input.maxSizes[2];
        return tpc_lib_api::GLUE_INCOMPATIBLE_OUTPUT_SIZE;
    }

    instance->indexSpaceRank = 2;
    instance->indexSpaceGeometry[0] = (input.maxSizes[0] + 127) / 128;
    instance->indexSpaceGeometry[1] = input.maxSizes[2];
    auto map_tensor = [](auto& pattern, uint64_t channels) {
        pattern.mapping[0].indexSpaceDim = 0;
        pattern.mapping[0].a = 128;
        pattern.mapping[0].start_b = 0;
        pattern.mapping[0].end_b = 127;
        // Every program reads/writes the complete channel dimension (1 or 2).
        pattern.mapping[1].indexSpaceDim = 0;
        pattern.mapping[1].a = 0;
        pattern.mapping[1].start_b = 0;
        pattern.mapping[1].end_b = channels - 1;
        pattern.mapping[2].indexSpaceDim = 1;
        pattern.mapping[2].a = 1;
        pattern.mapping[2].start_b = 0;
        pattern.mapping[2].end_b = 0;
    };
    map_tensor(instance->inputTensorAccessPattern[0], binary->gated ? 2 : 1);
    if (binary->backward) map_tensor(instance->inputTensorAccessPattern[1], 1);
    map_tensor(instance->outputTensorAccessPattern[0], output_channels);
    instance->kernel.paramsNr = 0;
    return tpc_lib_api::GLUE_SUCCESS;
}

extern "C" tpc_lib_api::GlueCodeReturn InstantiateTpcKernel(
    tpc_lib_api::HabanaKernelParams* params, tpc_lib_api::HabanaKernelInstantiation* instance
) {
    if (params->deviceId != ARENO_TPC_DEVICE) return tpc_lib_api::GLUE_NODE_NOT_FOUND;
    const KernelBinary* binary = nullptr;
    for (const auto& candidate : binaries) {
        if (std::strcmp(params->guid.name, candidate.name) == 0) {
            binary = &candidate;
            break;
        }
    }
    if (binary == nullptr) return tpc_lib_api::GLUE_NODE_NOT_FOUND;
    auto status = binary->family == 0 ? instantiate_activation(params, instance, binary)
        : binary->family == 1 ? instantiate_normalization(params, instance, *binary)
        : binary->family == 2 ? instantiate_linear(params, instance, *binary)
        : binary->family == 3 ? instantiate_optimizer(params, instance, *binary)
        : binary->family == 4 ? instantiate_quantized_optimizer(params, instance, *binary)
        : binary->family == 5 ? instantiate_factored_stats(params, instance, *binary)
        : binary->family == 6 ? instantiate_embedding(params, instance, *binary)
        : binary->family == 7 ? instantiate_attention(params, instance, *binary)
        : binary->family == 8 ? instantiate_paged_cache(params, instance, *binary)
        : binary->family == 9 ? instantiate_conv(params, instance, *binary)
        : binary->family == 10 ? instantiate_topk(params, instance, *binary)
        : binary->family == 11 ? instantiate_moe(params, instance, *binary)
        : binary->family == 12 ? instantiate_moe_align(params, instance, *binary)
        : binary->family == 13 ? instantiate_fused_moe(params, instance, *binary)
        : binary->family == 14 ? instantiate_kda_prepare(params, instance, *binary)
        : binary->family == 15 ? instantiate_kda(params, instance, *binary)
        : binary->family == 16 ? instantiate_state_update(params, instance, *binary)
        : instantiate_seg_la(params, instance, *binary);
    if (status != tpc_lib_api::GLUE_SUCCESS) return status;
    const auto capacity = instance->kernel.elfSize;
    instance->kernel.elfSize = binary->size;
    if (capacity < binary->size) return tpc_lib_api::GLUE_INSUFFICIENT_ELF_BUFFER;
    std::memcpy(instance->kernel.kernelElf, binary->data, binary->size);
    return tpc_lib_api::GLUE_SUCCESS;
}
